#!/bin/bash
#
# create the stats
#

app=localhost:50100

cmd="curl http://$app/vmstat/update/16/"
for col in r b ; do
		cmd="$cmd&procs\[$col\]=$RANDOM"
done
for col in swpd free buff cache ; do
		cmd="$cmd&memory\[$col\]=$RANDOM"
done
for col in si so ; do
		cmd="$cmd&swap\[$col\]=$RANDOM"
done
for col in bi bo ; do
		cmd="$cmd&io\[$col\]=$RANDOM"
done
for col in bo int ; do
		cmd="$cmd&system\[$col\]=$RANDOM"
done
for col in us sys id wa st ; do
		cmd="$cmd&cpu\[$col\]=$RANDOM"
done
cmd=`echo $cmd | sed -e "s/\/\&/\/\?/"`
echo $cmd
$cmd
echo

